// Login types
export const SEND_LOGIN_REQUEST = 'SEND_LOGIN_REQUEST'
export const SEND_LOGIN_SUCCESS = 'SEND_LOGIN_SUCCESS'
export const SEND_LOGIN_ERROR = 'SEND_LOGIN_ERROR'

// Register types
export const SEND_REGISTER_REQUEST = 'SEND_REGISTER_REQUEST'
export const SEND_REGISTER_SUCCESS = 'SEND_REGISTER_SUCCESS'
export const SEND_REGISTER_ERROR = 'SEND_REGISTER_ERROR'

// Product types
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'